#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.8.0
# Generated On: 7/3/2011 11:35 AM
# Generated By: sean.kearney
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname(“System.Windows.Forms”) | Out-Null
[reflection.assembly]::loadwithpartialname(“System.Drawing”) | Out-Null
#endregion

#region Generated Form Objects
$Form = New-Object System.Windows.Forms.Form
$Button0 = New-Object System.Windows.Forms.Button
$Button1 = New-Object System.Windows.Forms.Button
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#———————————————-
#Generated Event Script Blocks
#———————————————-
#Provide Custom Code for events specified in PrimalForms.
$handler_Button0_Click=
{
#TODO: Place custom script here
Quit
}

$handler_Button1_Click=
{
#TODO: Place custom script here
Quit
}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
$Form.WindowState = $InitialFormWindowState
}

#———————————————-
#region Generated Form Code
$Form.Text = “Keep 'Er Safe”
$Form.Name = “Form”
$Form.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 265
$System_Drawing_Size.Height = 265
$Form.ClientSize = $System_Drawing_Size

$Button0.TabIndex = 0
$Button0.Name = “Button0”

$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 240
$System_Drawing_Size.Height = 23
$Button0.Size = $System_Drawing_Size
$Button0.UseVisualStyleBackColor = $True
$Button0.Text = “Button0”

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 13
$Button0.Location = $System_Drawing_Point
$Button0.DataBindings.DefaultDataSourceUpdateMode = 0
$Button0.add_Click($handler_Button0_Click)

$Form.Controls.Add($Button0)

$Button1.TabIndex = 1
$Button1.Name = “Button1”

$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 240
$System_Drawing_Size.Height = 23
$Button1.Size = $System_Drawing_Size
$Button1.UseVisualStyleBackColor = $True
$Button1.Text = “Button1”

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 55
$Button1.Location = $System_Drawing_Point
$Button1.DataBindings.DefaultDataSourceUpdateMode = 0
$Button1.add_Click($handler_Button1_Click)

$Form.Controls.Add($Button1)

$Button1.TabIndex = 1
$Button1.Name = “Button1”

$System_Drawing_Size = New-Object System.Data.l
$System_Drawing_Size.Width = 240
$System_Drawing_Size.Height = 23
$Table1.Size = $System_Drawing_Size
$Table1.UseVisualStyleBackColor = $True
$Table1.Text = “Button1”

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 55
$Table1.Location = $System_Drawing_Point
$Table1.DataBindings.DefaultDataSourceUpdateMode = 0
$Table1.add_Click($handler_Table1_Click)

$Form.Controls.Add($Table1)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $Form.WindowState



#Init the OnLoad event to correct the initial state of the form
$Form.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$Form.ShowDialog()| Out-Null

} #End Function

function Quit {
}

#Call the Function
GenerateForm